### PR TITLE
Add compatibility fixes between Django v1.8 and v1.9

### PR DESCRIPTION
**Pull request by imanhodjaev**
Added `compat.py` to support Django v1.8 and v1.9 related imports for `GenericForeignKey`, `GenericTabularInline` and `get_model`. Also made changes related to code formatting for flake8.

Please review and give feedback if these changes useful.

### CODE REVIEW

**Comment by angvp** [comment]
Hello @imanhodjaev thanks for the PR .. I was doing the same effort days ago, but I didn't had the time to complete it, one little thing instead of using Django>=1.9 on tox.ini you should use Django<1.10 also, would you mind to squash some commits (tox and travis file) ?

**Comment by imanhodjaev** [comment]
@angvp I squashed five commits and changes tox config for Django v1.9 < v1.10 do I need to squash more commits?

**Comment by angvp** [comment]
Well, I don't want to be nitpicky with this, this is your first contribution, and it's really great, but for the next time, take these comments in consideration: 

- Read the file ```CONTRIBUTING.md``` you made your changes on ```master``` branch and your pushing against ```master``` here the README file properly says that you should do it against ```develop``` branch (so I should do merge against master and then rebase develop again against master to have the same flow again)
- Squash more your commits .. I got here 12 commits when you just 5 would be more than enough:
1.- changes in compat 
2.- refactor 
3.- tox 
4.- travis 
5.- flake8 ...

Again, thanks for your contribution!.

**Comment by imanhodjaev** [comment]
@angvp yessir for the next time I will pay more attention to the changes I make because it is a little annoying to walk through many little commits.

Thank you.

**Comment by angvp** [comment]
:+1: :smile:

**Pull request merged**
